name: 🐛 Bug 报告
description: 早起的小可爱有虫抓
labels: ['bug 🐛']

body:
  - type: textarea
    id: what-expected
    attributes:
      label: 预期是什么？
    validations:
      required: true

  - type: textarea
    id: actual-happened
    attributes:
      label: 实际发生了什么？
    validations:
      required: true

  - type: input
    id: sys-info
    attributes:
      label: 系统相关信息
      description: |
        请提供您的操作系统信息。
        请确保您使用的是[最新版本](https://github.com/Fatpandac/fuck_cqooc/releases)
      placeholder: 'OS: Linux'

  - type: textarea
    id: logs
    attributes:
      label: 额外信息
      description: 日志、报错等
      render: shell
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 这不是重复的 issue
      options:
        - label: 我已经搜索了[现有 issue](https://github.com/Fatpandac/fuck_cqooc/issues)，以确保该错误尚未被报告。
          required: true
